env:
  browser: false
  es2021: true
extends: standard-with-typescript
ignorePatterns:
  - reports/**
  - dist/**
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - ./tsconfig.json
    - ./tsconfig.eslint.json
rules: {}
