version: '3.4'

services:
  # main IDE container
  main:
    image: docker-build-registry:5000/${PKG_NAME}:ci
    working_dir: /workspace
    environment:
      PKG_NAME: ${PKG_NAME}
      NODE_TOOLS: ${NODE_TOOLS}
      TOOLS: ${TOOLS}
      CUSTOM_NODE_TOOLS: ${CUSTOM_NODE_TOOLS}
      CUSTOM_TOOLS: ${CUSTOM_TOOLS}
    build:
      context: ..
      dockerfile: Dockerfile
      target: ide
      args:
        PKG_NAME: ${PKG_NAME}
        NODE_TOOLS: ${NODE_TOOLS}
        TOOLS: ${TOOLS}
        CUSTOM_NODE_TOOLS: ${CUSTOM_NODE_TOOLS}
        CUSTOM_TOOLS: ${CUSTOM_TOOLS}

    volumes:
    # Update this to wherever you want VS Code to mount the folder of your project
    - ..:/workspace

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
