version: '3.4'

services:
  main:
    container_name: main
    environment:
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_REGION: ${AWS_REGION}
      AWS_ROLE_ARN: ${AWS_ROLE_ARN}
      AWS_WEB_IDENTITY_TOKEN_FILE: ${AWS_WEB_IDENTITY_TOKEN_FILE}
      AWS_STS_REGIONAL_ENDPOINTS: ${AWS_STS_REGIONAL_ENDPOINTS}

    build:
      cache_to:
        - type=registry,ref=docker-build-registry:5000/${PKG_NAME}:buildcache,mode=max
      cache_from:
        - type=registry,ref=docker-build-registry:5000/${PKG_NAME}:buildcache
    volumes:
      - /var/run/secrets/eks.amazonaws.com/serviceaccount/token:/var/run/secrets/eks.amazonaws.com/serviceaccount/token
