name: build

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  build:

    runs-on: [ self-hosted ]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image
        run: |
          docker buildx build --load \
                              --progress plain \
                              --cache-to type=registry,ref=docker-build-registry:5000/github-automation-app:build,mode=max \
                              --cache-from type=registry,ref=docker-build-registry:5000/github-automation-app:build \
                              -t docker-build-registry:5000/github-automation-app:$GITHUB_SHA .

      - name: ghcr.io login
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag docker-build-registry:5000/github-automation-app:$GITHUB_SHA \
            ghcr.io/$(echo $GITHUB_REPOSITORY_OWNER | awk '{print tolower($$0)}')/github-automation-app:$GITHUB_SHA

          docker images

          # authenticate to our registries
          docker push ghcr.io/$(echo $GITHUB_REPOSITORY_OWNER | awk '{print tolower($$0)}')/github-automation-app:$GITHUB_SHA
